CREATE TABLE ORDERS
(
    ID                      BIGINT NOT NULL PRIMARY KEY,
    USER_ID                 BIGINT NULL,
    STATUS                  INT NOT NULL,
    ORDERER_NAME            VARCHAR(255) NULL,
    ORDERER_EMAIL           VARCHAR(255) NULL,
    ORDERER_PHONE           VARCHAR(255) NULL,
    ORDERER_MOBILE          VARCHAR(255) NULL,
    USED_EMONEY_AMOUNT      INT NOT NULL,
    USED_COUPON_AMOUNT      INT DEFAULT 0 NOT NULL,
    ORDERED_DATE            TIMESTAMP NULL,
    PAID_DATE               TIMESTAMP NULL,
    REGISTERED_DATE         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_DATE           TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    MEMO                    VARCHAR(255) NULL,
    MEMO_CLIENT             TEXT NULL,
    USE_DEVICE              TINYINT NULL,
    HAS_REVIEW              VARCHAR(1) DEFAULT 'N' NULL
);

CREATE INDEX IDX_ORDERED_DATE   ON ORDERS(ORDERED_DATE);
CREATE INDEX IDX_STATUS         ON ORDERS(STATUS);
CREATE INDEX IDX_USER_ID        ON ORDERS(USER_ID);
CREATE INDEX REGISTERED_DATE    ON ORDERS(REGISTERED_DATE);
