CREATE TABLE TEAM (
      TEAM_ID BIGINT NOT NULL,
      NAME VARCHAR(255),
      PRIMARY KEY (TEAM_ID)
);

INSERT INTO TEAM (TEAM_ID, NAME) VALUES (1, 'TEAM A');
INSERT INTO TEAM (TEAM_ID, NAME) VALUES (2, 'TEAM B');
