spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;
    username: sa
    password:
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 5
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-weblog

  h2:
    console:
      enabled: true
      path: /h2-console